-- 测试数据库表结构（H2兼容）
-- 用于集成测试

-- API密钥表
CREATE TABLE IF NOT EXISTS api_key (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key_name VARCHAR(255),
    api_key VARCHAR(255) UNIQUE NOT NULL,
    api_secret VARCHAR(255),
    law_firm_name VARCHAR(255),
    enabled BOOLEAN DEFAULT true,
    expires_at TIMESTAMP,
    last_used_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 项目数据表
CREATE TABLE IF NOT EXISTS client_matter (
    id VARCHAR(255) PRIMARY KEY,
    law_firm_matter_id BIGINT,
    client_id BIGINT,
    client_name VARCHAR(255),
    source_api_key_id BIGINT,
    matter_data TEXT,
    scopes VARCHAR(255),
    valid_days INTEGER,
    expires_at TIMESTAMP,
    access_token VARCHAR(255),
    access_url VARCHAR(500),
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- client_matter表索引（提高查询性能）
-- 生产环境PostgreSQL请使用: CREATE INDEX IF NOT EXISTS idx_xxx ON table (column);
CREATE INDEX IF NOT EXISTS idx_client_matter_law_firm_matter_id ON client_matter (law_firm_matter_id);
CREATE INDEX IF NOT EXISTS idx_client_matter_source_api_key_id ON client_matter (source_api_key_id);
CREATE INDEX IF NOT EXISTS idx_client_matter_access_token ON client_matter (access_token);
CREATE INDEX IF NOT EXISTS idx_client_matter_client_id ON client_matter (client_id);
CREATE INDEX IF NOT EXISTS idx_client_matter_status ON client_matter (status);
CREATE UNIQUE INDEX IF NOT EXISTS uk_client_matter_source_law_firm_matter_id
    ON client_matter (source_api_key_id, law_firm_matter_id);

-- 访问日志表
CREATE TABLE IF NOT EXISTS access_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id VARCHAR(255),
    client_id BIGINT,
    access_token VARCHAR(255),
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    access_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 通知记录表
CREATE TABLE IF NOT EXISTS notification_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id VARCHAR(255),
    client_id BIGINT,
    law_firm_matter_id BIGINT,
    client_name VARCHAR(255),
    notification_type VARCHAR(50),
    recipient VARCHAR(255),
    content TEXT,
    status VARCHAR(50),
    error_code VARCHAR(50),
    error_message VARCHAR(500),
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    next_retry_at TIMESTAMP,
    last_retry_at TIMESTAMP,
    sent_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 回调出站任务表
CREATE TABLE IF NOT EXISTS callback_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id VARCHAR(255),
    callback_type VARCHAR(50) NOT NULL,
    callback_url VARCHAR(500) NOT NULL,
    callback_payload CLOB,
    status VARCHAR(20) DEFAULT 'PENDING',
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 12,
    next_retry_at TIMESTAMP,
    last_attempt_at TIMESTAMP,
    last_error CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_callback_task_status ON callback_task (status);
CREATE INDEX IF NOT EXISTS idx_callback_task_next_retry_at ON callback_task (next_retry_at);
CREATE INDEX IF NOT EXISTS idx_callback_task_matter_id ON callback_task (matter_id);

-- 客户文件表
CREATE TABLE IF NOT EXISTS client_file (
    id VARCHAR(255) PRIMARY KEY,
    matter_id VARCHAR(255),
    client_id BIGINT,
    file_name VARCHAR(255),
    file_size BIGINT,
    file_type VARCHAR(100),
    file_category VARCHAR(50),
    description VARCHAR(500),
    storage_path VARCHAR(500),
    file_source VARCHAR(20) DEFAULT 'CLIENT_UPLOAD',
    file_hash VARCHAR(64),
    uploaded_at TIMESTAMP,
    status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 系统配置表
CREATE TABLE IF NOT EXISTS sys_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_key VARCHAR(100) UNIQUE NOT NULL,
    config_value TEXT,
    config_type VARCHAR(50) DEFAULT 'STRING',
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 管理员用户表
CREATE TABLE IF NOT EXISTS admin_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    real_name VARCHAR(100),
    email VARCHAR(200),
    phone VARCHAR(20),
    enabled BOOLEAN DEFAULT true,
    failed_login_count INTEGER DEFAULT 0,
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    last_login_ip VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 通知模板表
CREATE TABLE IF NOT EXISTS notification_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_code VARCHAR(50) UNIQUE NOT NULL,
    template_name VARCHAR(100) NOT NULL,
    template_type VARCHAR(20) NOT NULL,
    subject VARCHAR(200),
    template_content TEXT NOT NULL,
    template_variables VARCHAR(500),
    provider VARCHAR(50),
    sign_name VARCHAR(100),
    enabled BOOLEAN DEFAULT true,
    description VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 管理员登录日志表
CREATE TABLE IF NOT EXISTS admin_login_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(50),
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    login_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    success BOOLEAN DEFAULT true,
    failure_reason VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 下载日志表
CREATE TABLE IF NOT EXISTS download_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matter_id VARCHAR(50),
    file_id VARCHAR(50),
    file_name VARCHAR(255),
    client_id BIGINT,
    access_token VARCHAR(100),
    ip_address VARCHAR(50),
    user_agent VARCHAR(500),
    download_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

-- 函件验证表
CREATE TABLE IF NOT EXISTS letter_verification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter_id BIGINT NOT NULL,
    source_api_key_id BIGINT,
    application_no VARCHAR(50) NOT NULL,
    verification_code VARCHAR(100) NOT NULL,
    letter_type VARCHAR(50),
    letter_type_name VARCHAR(100),
    target_unit VARCHAR(200),
    lawyer_names VARCHAR(500),
    firm_name VARCHAR(200),
    matter_name VARCHAR(200),
    approved_at TIMESTAMP,
    printed_at TIMESTAMP,
    valid_until TIMESTAMP,
    remark CLOB,
    verify_count INTEGER DEFAULT 0,
    last_verify_at TIMESTAMP,
    last_verify_ip VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_letter_verification_application_no ON letter_verification (application_no);
CREATE INDEX IF NOT EXISTS idx_letter_verification_letter_id ON letter_verification (letter_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_letter_verification_source_application_no
    ON letter_verification (source_api_key_id, application_no);

-- 插入测试API密钥（H2兼容语法）
MERGE INTO api_key (id, key_name, api_key, api_secret, law_firm_name, enabled, expires_at)
KEY (api_key)
VALUES (1, '测试律所API密钥', 'test-api-key-12345678901234567890', 'test-api-secret', '测试律师事务所', true, NULL);

-- 插入测试系统配置（H2兼容语法，使用MERGE避免重复）
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('system.name', '客户服务系统', 'STRING', '系统名称');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('system.version', '1.0.0', 'STRING', '系统版本');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('system.base-url', 'http://localhost:8081', 'STRING', '系统基础URL');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('notification.email.enabled', 'false', 'BOOLEAN', '邮件通知是否启用');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('notification.sms.enabled', 'false', 'BOOLEAN', '短信通知是否启用');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('notification.wechat.enabled', 'false', 'BOOLEAN', '微信通知是否启用');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('file.max-size', '10485760', 'NUMBER', '最大文件大小（字节）');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('file.storage.type', 'local', 'STRING', '文件存储类型');
MERGE INTO sys_config (config_key, config_value, config_type, description) KEY (config_key)
VALUES ('api.token-expire-days', '30', 'NUMBER', 'Token默认有效期（天）');
