export const ADMIN_SYSTEM_CONFIG_TEXTS = {
  intro: '品牌、门户与系统参数；高级项在对应页签。',
  tabs: {
    brand: '品牌配置',
    portal: '门户配置',
    system: '系统配置',
    advanced: '高级配置',
  },
  miniStats: {
    brandFields: '品牌字段',
    portalFields: '门户字段',
    systemConfigItems: '系统配置项',
  },
  completionTitle: '配置完整度',
  completion: {
    brand: '品牌配置',
    portal: '门户配置',
    system: '系统配置项',
  },
  brand: {
    systemNameTitle: '系统名称',
    logoTitle: 'Logo 设置',
    appNameLabel: '系统全称（浏览器标题）',
    shortNameLabel: '系统简称（中文）',
    shortNameEnLabel: '系统简称（英文）',
    logoUrlLabel: 'Logo 图片地址',
    logoPreviewLabel: 'Logo 预览',
    appNamePlaceholder: '如：XX律师事务所客户服务系统',
    appNameHint: '显示在浏览器标签页标题',
    shortNamePlaceholder: '如：XX律所客服',
    shortNameHint: '显示在管理后台侧边栏',
    shortNameEnPlaceholder: '如：XX Law Service（可选）',
    shortNameEnHint: '可选字段；如需双语品牌展示，可显示在管理后台侧边栏下方',
    logoPlaceholder: '如：/logo.png 或 https://...',
    logoHint: '支持相对路径或完整 URL',
    logoEmpty: '暂未设置 Logo',
  },
  portal: {
    lawFirmTitle: '律所信息',
    pageContentTitle: '页面内容',
    lawFirmNameLabel: '律所名称',
    websiteLabel: '律所官网',
    sloganLabel: '首页标语',
    eyebrowLabel: '门户页英文眉标（可选）',
    accessNoticeLabel: '门户页客户说明（公开页主文案）',
    staffEntryLabelText: '工作人员入口（页脚小字链）',
    icpLabel: 'ICP 备案号',
    copyrightLabel: '版权信息',
    lawFirmNamePlaceholder: '如：XX律师事务所',
    lawFirmNameHint: '显示在门户页面头部和底部',
    websitePlaceholder: '如：https://www.example.com',
    websiteHint: '点击律所名称时跳转的链接',
    sloganPlaceholder: '如：专业 · 诚信 · 高效',
    sloganHint: '显示在门户欢迎区域',
    eyebrowPlaceholder: '留空则使用品牌配置中的「系统英文简称」',
    eyebrowHint: '显示在公开门户页主标题上方',
    accessNoticePlaceholder: '说明客户如何通过律师发送的链接使用本系统',
    accessNoticeHint: '显示在公开门户页中央；留空则不显示该段落',
    staffEntryPlaceholder: '如：工作人员入口；留空则不显示',
    staffEntryHint: '显示在公开门户页底部，链向管理后台登录；勿写敏感信息',
    icpPlaceholder: '如：京ICP备XXXXXXXX号',
    icpHint: '显示在页面底部，可选',
    copyrightPlaceholder: '如：© 2024 XX律师事务所',
    copyrightHint: '显示在页面底部',
  },
  system: {
    systemUrlTitle: '系统地址',
    callbackTitle: '回调配置',
    advancedTitle: '所有配置项',
    advancedDesc: '保留底层配置入口，便于管理未在可视化卡片中暴露的参数。',
    baseUrlLabel: '系统基础 URL（必填）',
    callbackEnabledLabel: '启用回调',
    callbackUrlLabel: '律所系统地址',
    callbackSecretLabel: '回调密钥',
    callbackAllowInternalLabel: '允许内网回调',
    addConfig: '新增配置',
    searchKeyLabel: '配置键',
    searchTypeLabel: '配置类型',
    keyLabel: '配置键',
    valueLabel: '配置值',
    typeLabel: '配置类型',
    descriptionLabel: '描述',
    stringOption: '字符串',
    numberOption: '数字',
    booleanOption: '布尔值',
    jsonOption: 'JSON',
    booleanTrue: '是',
    booleanFalse: '否',
    baseUrlPlaceholder: '如：https://client.yourfirm.com',
    baseUrlHint: '客户服务系统的外网访问地址，用于生成客户访问链接。',
    baseUrlExample: '示例：https://client.yourfirm.com 或 http://192.168.1.100:8080',
    callbackEnabledHint: '当客户访问项目或下载文件时，回调管理系统记录访问日志。',
    callbackUrlPlaceholder: '如：http://192.168.1.100/api',
    callbackUrlHint: '新主链路下通常无需手工填写。管理系统推送项目时会自动把自己的回调地址绑定到该项目；这里只作为历史项目或特殊覆盖场景兜底。',
    callbackSecretPlaceholder: '与管理系统约定的回调校验密钥',
    callbackSecretHint: '新主链路下通常优先复用当前项目来源 API key 的 Secret 作为回调校验；这里只作为旧链路或手工覆盖兜底。固定公网 IP 场景如需额外白名单控制，请在网关或反向代理侧配置。',
    callbackAllowInternalYes: '当前允许回调到内网地址，适用于企业内网部署。',
    callbackAllowInternalNo: '当前禁止回调到内网地址，仅允许公网地址。',
    searchKeyPlaceholder: '请输入配置键',
    searchTypePlaceholder: '请选择配置类型',
    modalEditTitle: '编辑配置',
    modalCreateTitle: '新增配置',
    valueJsonPlaceholder: '请输入 JSON 格式的配置值',
    valueBooleanPlaceholder: '请选择',
    valueNumberPlaceholder: '请输入数字',
    valueDefaultPlaceholder: '请输入配置值',
    descriptionPlaceholder: '请输入配置描述',
    saveSaving: '保存中...',
    saveSaved: '已保存',
    saveFailed: '保存失败',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
  },
  table: {
    configKey: '配置键',
    configValue: '配置值',
    type: '类型',
    description: '描述',
    action: '操作',
    edit: '编辑',
  },
  validation: {
    configKeyRequired: '请填写配置键',
    configValueRequired: '请填写配置值',
  },
  feedback: {
    loadConfigFailed: '加载配置失败',
    unknownError: '未知错误',
    deleteFailed: '删除失败',
    operationFailed: '操作失败',
  },
} as const

export const ADMIN_NOTIFICATION_SETTINGS_TEXTS = {
  intro: '邮件 / 短信 / 微信渠道与参数；保存后生效。',
  stats: {
    enabledChannels: '启用渠道',
    email: '邮件',
    sms: '短信',
    wechat: '微信',
    on: 'ON',
    off: 'OFF',
  },
  overviewTitle: '配置说明',
  overviewDescPrefix: '配置存数据库；缺键时回退',
  overviewTag: '即时生效',
  overviewLink: '管理通知模板',
  channelSectionTitle: '通知通道',
  channel: {
    enabled: '已启用',
    disabled: '已禁用',
  },
  email: {
    title: '邮件通知',
    desc: '用于项目变更通知、访问链接发送和正式邮件触达。',
    accessStatusLabel: '接入状态',
    senderIdentityLabel: '发件身份',
    statusConfigured: 'SMTP 已配置',
    statusPending: '等待配置',
    identityUnset: '未设置',
    smtpTitle: 'SMTP 服务器配置',
    smtpHostLabel: 'SMTP 服务器地址',
    smtpPortLabel: 'SMTP 端口',
    smtpUserLabel: 'SMTP 用户名',
    smtpPasswordLabel: 'SMTP 密码',
    smtpHostPlaceholder: '请输入 SMTP 服务器地址（如：smtp.example.com）',
    smtpPortPlaceholder: '请输入 SMTP 端口（如：587）',
    smtpUserPlaceholder: '请输入 SMTP 用户名（通常是邮箱地址）',
    smtpPasswordPlaceholder: '请输入 SMTP 密码（或授权码）',
    smtpAlert: 'SMTP 配置保存后立即生效，无需重启服务。若通过环境变量 SPRING_MAIL_* 覆盖，则环境变量优先。',
    senderTitle: '发件人信息',
    senderEmailLabel: '发件人邮箱',
    senderNameLabel: '发件人名称',
    senderEmailPlaceholder: '请输入发件人邮箱（如：noreply@example.com）',
    senderNamePlaceholder: '请输入发件人名称（如：客户服务系统）',
    saveButton: '保存邮件配置',
    saveSuccess: '邮件配置已生效，SMTP 参数已同步更新',
    enabledSuccess: '邮件通知通道已启用',
    disabledSuccess: '邮件通知通道已禁用',
  },
  sms: {
    title: '短信通知',
    desc: '适合高到达率提醒，注意模板字段和服务商控制台保持严格一致。',
    providerLabel: '服务商',
    providerMetaLabel: '服务商',
    templateMetaLabel: '模板映射',
    aliyunLabel: '阿里云',
    tencentLabel: '腾讯云',
    unset: '未设置',
    accessKeyIdLabel: 'Access Key ID',
    accessKeySecretLabel: 'Access Key Secret',
    signNameLabel: '签名名称',
    templateCodeLabel: '模板代码',
    endpointLabel: 'API 端点',
    secretIdLabel: 'Secret ID',
    secretKeyLabel: 'Secret Key',
    appIdLabel: '应用ID',
    templateIdLabel: '模板ID',
    regionLabel: '区域',
    providerPlaceholder: '请选择短信服务商',
    accessKeyIdPlaceholder: '请输入阿里云 Access Key ID',
    accessKeySecretPlaceholder: '请输入阿里云 Access Key Secret',
    signNamePlaceholder: '请输入短信签名名称',
    templateCodePlaceholder: '请输入短信模板代码',
    endpointPlaceholder: '请输入 API 端点（默认：dysmsapi.aliyuncs.com）',
    optionalHint: '可选，留空使用默认值',
    secretIdPlaceholder: '请输入腾讯云 Secret ID',
    secretKeyPlaceholder: '请输入腾讯云 Secret Key',
    appIdPlaceholder: '请输入腾讯云短信应用ID',
    templateIdPlaceholder: '请输入短信模板ID',
    regionPlaceholder: '请输入区域（默认：ap-beijing）',
    saveButton: '保存短信配置',
    saveSuccess: '短信配置已生效，通道参数已同步更新',
    enabledSuccess: '短信通知通道已启用',
    disabledSuccess: '短信通知通道已禁用',
  },
  wechat: {
    title: '微信通知',
    desc: '适合模板消息推送，默认模板可在这里维护，复杂内容建议交给模板库。',
    credentialLabel: '公众号凭证',
    defaultTemplateLabel: '默认模板',
    appIdLabel: 'AppID',
    appSecretLabel: 'AppSecret',
    templateLabel: '模板ID',
    appIdFilled: '已填 AppID',
    credentialPending: '待配置',
    templateUnset: '未设置',
    appIdPlaceholder: '请输入微信公众号 AppID',
    appSecretPlaceholder: '请输入微信公众号 AppSecret',
    templatePlaceholder: '请输入微信模板消息ID（可选，也可在通知模板管理中配置）',
    templateHint: '可以在通知模板管理页面配置更细的模板内容。',
    saveButton: '保存微信配置',
    saveSuccess: '微信配置已生效',
    enabledSuccess: '微信通知通道已启用',
    disabledSuccess: '微信通知通道已禁用',
  },
} as const

export const ADMIN_SYSTEM_MAINTENANCE_TEXTS = {
  intro: '状态、升级、备份与日志；按需刷新。',
  actions: {
    refreshStatus: '刷新状态',
    confirmBackup: '确认备份',
    cancel: '取消',
    download: '下载',
    remove: '移除',
  },
  overview: {
    database: '数据库连接',
    storage: '文件存储',
    backups: '备份文件',
    version: '版本状态',
    waiting: '待检查',
    upgradeable: '可升级',
    latest: '最新',
    unchecked: '未检查',
    normal: '正常',
    abnormal: '异常',
    available: '可用',
  },
  cards: {
    databaseTitle: '数据库状态',
    storageTitle: '文件存储',
    serverTitle: '服务器信息',
    connectedLabel: '连接状态',
    databaseSizeLabel: '数据库大小',
    fileCountLabel: '文件数量',
    storageUsageLabel: '占用空间',
    storagePathLabel: '存储路径',
    javaVersionLabel: 'Java 版本',
    osLabel: '操作系统',
    cpuLabel: 'CPU 核心',
    memoryLabel: '可用内存',
    serverTimeLabel: '服务器时间',
    recordsSuffix: '条',
    filesSuffix: '个',
    cpuSuffix: '核',
    memorySuffix: 'MB',
  },
  sections: {
    databaseStatus: '数据库状态',
    storageStatus: '文件存储',
    serverInfo: '服务器信息',
    systemUpgrade: '系统升级',
    upgradeCheckTitle: '升级与版本检查',
    upgradeCheckDesc: '先确认当前版本与远端版本差异，再决定是否进入升级指南。',
    backupTitle: '数据备份',
    backupManageTitle: '备份管理',
    backupManageDesc: '页面内可直接创建、下载和删除备份文件，用于升级前留档和恢复准备。',
    logsTitle: '日志管理',
    logsDesc: '登录日志和下载日志按时间与对象筛选，便于快速排查异常行为。',
    cliTitle: '命令行操作（高级）',
    cliManageTitle: '命令行操作',
    cliManageDesc: '保留给熟悉部署环境的管理员，用于升级、备份、查看日志和重启服务。',
  },
  upgrade: {
    checkUpdates: '检查更新',
    currentVersion: '当前版本',
    remoteVersion: '远端版本',
    decision: '升级判断',
    suggestUpgrade: '建议进入升级流程',
    alreadyLatest: '当前已是最新版本',
    waitingCheck: '等待检查',
    releaseNotes: '查看更新日志',
    newVersion: '发现新版本',
    latestVersionMessage: '已是最新版本',
    failedTitle: '检查失败',
    guideButton: '查看升级指南',
    guideTitle: '升级说明',
    guideItems: [
      '容器化部署需要在服务器上手动执行升级命令',
      '点击“查看升级指南”获取具体操作步骤',
      '升级过程中服务可能会短暂中断',
      '建议在低峰期执行升级操作',
    ],
    guideModalTitle: '升级指南',
    guideAlert: '请在服务器上执行以下命令完成升级',
    copyAlertTitle: '命令已自动复制到剪贴板',
    copyAlertDesc: '您可以直接在终端中粘贴执行（记得修改路径为实际项目目录）',
    copyAgain: '重新复制',
    copyNow: '复制命令',
    githubReleases: '查看 GitHub Releases',
    acknowledged: '知道了',
    stepsTitle: '操作步骤：',
  },
  backup: {
    create: '创建备份',
    noteTitle: '备份说明',
    noteDesc: '点击「创建备份」会导出数据库中的所有数据为 SQL 文件。建议定期备份，特别是在升级系统前。',
    count: '当前备份数',
    suggestion: '建议动作',
    suggestionValue: '升级前先创建新备份',
    confirmDelete: '确定删除此备份？',
    successPrefix: '备份创建成功：',
    failed: '备份失败',
    removed: '备份文件已移除',
    tableFilename: '文件名',
    tableSize: '大小',
    tableCreatedAt: '创建时间',
    tableAction: '操作',
  },
  logs: {
    hint: '优先按时间范围收窄结果，再导出 CSV。',
    loginTab: '登录日志',
    downloadTab: '下载日志',
    startLabel: '开始时间',
    endLabel: '结束时间',
    matterIdLabel: '项目ID',
    successTag: '成功',
    failureTag: '失败',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
    loadLoginFailed: '加载登录日志失败',
    loadDownloadFailed: '加载下载日志失败',
    exportFailed: '导出失败',
    startPlaceholder: '选择开始时间',
    endPlaceholder: '选择结束时间',
    matterIdPlaceholder: '输入项目ID',
    exportCsv: '导出 CSV',
  },
  cli: {
    upgrade: '一键升级',
    backup: '命令行备份',
    logs: '查看日志',
    restart: '重启服务',
    upgradeDesc: '自动执行：备份 → 拉取代码 → 重建镜像 → 重启服务',
    backupDesc: '备份数据库 + 文件 + 配置到 backups/ 目录',
  },
  feedback: {
    requestTimeout: '请求超时，请稍后重试',
    updateFound: '已发现可执行升级的新版本',
    alreadyLatest: '当前已是最新版本',
    guideLoadFailed: '获取升级指南失败',
    noCommands: '当前暂无可复制的升级命令',
  },
} as const

export const ADMIN_INITIAL_SETUP_TEXTS = {
  intro: '品牌与门户文案；完成后可在系统配置中补充高级项。',
  actions: {
    systemInfo: '查看系统信息',
    systemConfig: '前往系统配置',
    saveSetup: '保存初始化配置',
  },
  status: {
    pathLabel: '交付路径',
    pathValue: '首次初始化 → 系统信息 → 系统配置',
    initialized: '当前站点已完成基础品牌初始化，可继续微调或重新保存。',
    pending: '当前仍接近默认品牌配置，建议在正式交付前完成初始化。',
  },
  sections: {
    brandInit: '基础品牌初始化',
    preview: '效果预览',
    previewUsage: '用于门户首页、帮助页、登录页和后台导航中的统一品牌表达。',
    nextStep: '下一步建议',
  },
  placeholders: {
    appName: '例如：某某律师事务所客户服务系统',
    appShortName: '例如：某某律所客服',
    appShortNameEn: '例如：Law Firm Clients',
    logoUrl: '可填写 /logo.png 或完整 https:// URL',
    lawFirmName: '例如：某某律师事务所',
    lawFirmWebsite: '例如：https://www.example.com',
    appSlogan: '例如：专业事项，一个清晰的客户入口',
    portalEyebrowEn: '留空则使用上方「系统简称（英文）」',
    portalAccessNotice: '公开门户页主文案',
    staffEntryLabel: '留空则不显示',
    icpLicense: '例如：京ICP备12345678号-1',
    copyright: '例如：© 2026 某某律师事务所',
  },
  preview: {
    logoEmpty: '未设置',
    icpEmpty: '未设置ICP备案号',
  },
  nextSteps: [
    '初始化完成后，可进入“系统信息”页确认版本和文档入口是否齐全。',
    '再进入“系统配置”补充基础 URL、回调和通知策略。',
    '正式交付前，建议执行一次快速 API 冒烟测试。',
  ],
  validation: {
    appNameRequired: '请先填写系统全称',
  },
  saveDescription: '首次初始化向导配置',
} as const

export const ADMIN_MATTER_DETAIL_TEXTS = {
  fallbackTitle: '项目详情',
  heroText: '标识、状态、有效期与访问信息。',
  sections: {
    basicInfo: '基本信息',
    accessInfo: '访问信息',
    matterData: '案件数据',
  },
  fields: {
    matterId: '项目ID',
    lawFirmMatterId: '律所项目ID',
    clientId: '客户ID',
    clientName: '客户名称',
    status: '状态',
    validDays: '有效期（天）',
    expiresAt: '过期时间',
    scopes: '权限范围',
    createdAt: '创建时间',
    updatedAt: '更新时间',
    accessUrl: '访问链接',
    accessToken: '访问令牌',
  },
  actions: {
    copy: '复制',
    show: '显示',
    hide: '隐藏',
    revoke: '撤销访问',
  },
  feedback: {
    invalidId: '项目ID无效',
    loadFailed: '加载项目详情失败',
    revokeFailed: '撤销项目失败',
    emptyData: '无数据',
  },
} as const

export const ADMIN_LAYOUT_TEXTS = {
  update: {
    unknownVersion: '未知版本',
    releaseNotesTitleSuffix: ' 更新内容',
    emptyReleaseNotes: '暂无更新说明',
    missingVersion: '无法获取版本号',
    ignoredVersion: '已忽略此版本，下次有新版本时会再次提醒',
  },
  menu: {
    fileManagement: '文件管理',
    initialSetup: '首次初始化',
    systemInfo: '系统信息',
    letterVerification: '函件验证',
    notificationTemplates: '通知模板',
    apiKeyManagement: 'API密钥管理',
    systemConfig: '系统配置',
    systemMaintenance: '系统维护',
  },
  feedback: {
    logoutFailed: '退出登录失败',
  },
} as const

export const ADMIN_MATTER_LIST_TEXTS = {
  intro: '查看状态、有效期与访问链接；支持筛选与刷新。',
  actions: {
    refreshData: '刷新数据',
    view: '查看',
    revoke: '撤销',
  },
  stats: {
    total: '总项目数',
    active: '有效访问',
    expired: '已过期',
    revoked: '已撤销',
  },
  filter: {
    title: '筛选',
    clientIdLabel: '客户ID',
    clientIdPlaceholder: '请输入客户ID',
    statusLabel: '状态',
    statusPlaceholder: '请选择状态',
    dateRangeLabel: '时间范围',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
  },
  statusOptions: {
    active: '有效',
    expired: '已过期',
    revoked: '已撤销',
  },
  table: {
    matterId: '项目ID',
    clientName: '客户名称',
    status: '状态',
    validDays: '有效期（天）',
    expiresAt: '过期时间',
    accessUrl: '访问链接',
    createdAt: '创建时间',
    action: '操作',
  },
  feedback: {
    loadFailed: '加载项目列表失败',
    revokeFailed: '撤销项目失败',
  },
} as const

export const ADMIN_LETTER_VERIFICATION_TEXTS = {
  intro: '查询函件验证记录与状态；可展开统计。',
  stats: {
    total: '总记录数',
    active: '有效',
    expired: '已过期',
    revoked: '已撤销',
  },
  filter: {
    title: '筛选',
    statusLabel: '状态',
    statusPlaceholder: '请选择状态',
    keywordLabel: '关键词',
    keywordPlaceholder: '编号/律所/律师/接收单位',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
    revocablePrefix: '可撤销 ',
    revocableSuffix: ' 条',
  },
  table: {
    title: '记录列表',
    applicationNo: '函件编号',
    letterTypeName: '函件类型',
    firmName: '律师事务所',
    lawyerNames: '出函律师',
    targetUnit: '接收单位',
    status: '状态',
    validUntil: '有效期至',
    verifyCount: '验证次数',
    lastVerifyAt: '最后验证',
    action: '操作',
    ipPrefix: 'IP: ',
  },
  actions: {
    detail: '详情',
    invalidate: '失效',
  },
  drawer: {
    title: '函件验证详情',
    applicationNo: '函件编号',
    letterType: '函件类型',
    firmName: '律师事务所',
    lawyerNames: '出函律师',
    targetUnit: '接收单位',
    matterName: '关联项目',
    verifyCount: '验证次数',
    approvedAt: '审批时间',
    printedAt: '盖章时间',
    validUntil: '有效期至',
    expiredSuffix: '（已过期）',
    lastVerifyAt: '最后验证时间',
    lastVerifyIp: '最后验证IP',
    remark: '备注',
    createdAt: '创建时间',
  },
  statusOptions: {
    active: '有效',
    revoked: '已撤销',
    expired: '已过期',
    unknown: '未知',
  },
  feedback: {
    loadFailed: '加载数据失败',
    loadStatsFailed: '加载统计数据失败',
    revokeFailed: '撤销失败',
  },
} as const

export const ADMIN_PROFILE_TEXTS = {
  intro: '资料与安全设置。',
  stats: {
    identity: '账户身份',
    username: '用户名',
    email: '邮箱',
    password: '密码',
    passwordAdvice: '定期更换',
    adminFallback: '管理员',
    unbound: '未绑定',
  },
  identity: {
    roleDesc: '后台账号。',
    username: '用户名',
    realName: '真实姓名',
    email: '邮箱',
    lastLoginAt: '最后登录',
  },
  security: {
    title: '安全设置',
    note: '建议定期轮换密码并避免重复使用旧密码。',
    passwordTab: '修改密码',
    oldPasswordLabel: '当前密码',
    oldPasswordPlaceholder: '请输入当前使用的密码',
    newPasswordLabel: '新密码',
    newPasswordPlaceholder: '请输入新密码（至少8位）',
    confirmPasswordLabel: '确认新密码',
    confirmPasswordPlaceholder: '请再次输入新密码',
    submit: '修改密码',
  },
  validation: {
    confirmRequired: '请再次输入新密码',
    confirmMismatch: '两次输入的密码不一致',
    oldPasswordRequired: '请输入当前密码',
    newPasswordRequired: '请输入新密码',
    passwordMinLength: '密码长度至少为8位',
  },
} as const

export const ADMIN_FILE_MANAGEMENT_TEXTS = {
  intro: '按条件检索；支持批量移除与过期清理。',
  actions: {
    batchRemove: '批量移除',
    cleanupExpired: '清理过期文件',
    detail: '详情',
    cleanupTitle: '清理过期文件',
    cleanupRange: '清理范围',
    cleanupHelpPrefix: '清理 ',
    cleanupHelpSuffix: ' 天前标记为删除的文件（物理删除）',
  },
  stats: {
    total: '总文件数',
    active: '活跃文件',
    deleted: '已删除',
    storage: '存储空间',
  },
  filter: {
    title: '筛选',
    matterIdLabel: '项目ID',
    matterIdPlaceholder: '输入项目ID',
    statusLabel: '状态',
    statusPlaceholder: '选择状态',
    categoryLabel: '类别',
    categoryPlaceholder: '选择类别',
    keywordLabel: '关键字',
    keywordPlaceholder: '文件名/描述',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
    selectedPrefix: '已选 ',
    selectedSuffix: ' 条',
  },
  statusOptions: {
    active: '活跃',
    deleted: '已删除',
  },
  categories: {
    evidence: '证据材料',
    contract: '合同文件',
    idCard: '身份证件',
    other: '其他',
  },
  table: {
    title: '文件列表',
    fileName: '文件名',
    matterId: '项目ID',
    size: '大小',
    category: '类别',
    status: '状态',
    uploadedAt: '上传时间',
    action: '操作',
  },
  detail: {
    title: '文件详情',
    fileId: '文件ID',
    fileName: '文件名',
    matterId: '项目ID',
    fileSize: '文件大小',
    fileType: '文件类型',
    fileCategory: '文件类别',
    storagePath: '存储路径',
    description: '描述',
    uploadedAt: '上传时间',
    status: '状态',
  },
  confirm: {
    batchRemoveContentPrefix: '确定要移除已选中的 ',
    batchRemoveContentMiddle: ' 份文件吗？此操作不可恢复。',
    cancel: '取消',
  },
  feedback: {
    statsLoadFailed: '加载统计数据失败',
    listLoadFailed: '加载文件列表失败',
    batchRemovedPrefix: '成功删除 ',
    batchRemovedSuffix: ' 个文件',
    cleanedPrefix: '成功清理 ',
    cleanedSuffix: ' 个文件',
  },
} as const

export const ADMIN_NOTIFICATION_TEMPLATE_TEXTS = {
  intro: '短信 / 微信 / 邮件模板与服务商映射。',
  actions: {
    create: '新增模板',
    edit: '编辑',
  },
  guide: {
    title: '模板使用说明',
    tag: '统一管理',
    items: [
      '发送前替换变量；短信/微信需与平台侧模板一致。',
      '邮件支持 HTML。',
    ],
  },
  stats: {
    total: '模板总数',
    enabled: '启用中',
    channelMix: '短信 / 微信 / 邮件',
    providerMapping: '服务商映射',
  },
  filter: {
    title: '筛选',
    typeLabel: '模板类型',
    providerLabel: '服务商',
    statusLabel: '状态',
    typePlaceholder: '请选择模板类型',
    providerPlaceholder: '请选择服务商',
    statusPlaceholder: '请选择状态',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
    enabledPrefix: '启用 ',
    enabledSuffix: ' 条',
  },
  table: {
    title: '模板列表',
    id: 'ID',
    name: '模板名称',
    type: '模板类型',
    code: '模板代码',
    provider: '服务商',
    signName: '签名名称',
    content: '模板内容',
    status: '状态',
    createdAt: '创建时间',
    action: '操作',
  },
  modal: {
    editTitle: '编辑模板',
    createTitle: '新增模板',
    nameLabel: '模板名称',
    typeLabel: '模板类型',
    codeLabel: '模板代码',
    providerLabel: '服务商',
    signNameLabel: '签名名称',
    contentLabel: '模板内容',
    variablesLabel: '模板变量',
    statusLabel: '状态',
    descriptionLabel: '描述',
    enabled: '启用',
    disabled: '禁用',
    namePlaceholder: '请输入模板名称',
    typePlaceholder: '请选择模板类型',
    providerPlaceholder: '请选择服务商',
    signNamePlaceholder: '请输入签名名称（在服务商平台申请的签名）',
    variablesPlaceholder: '请输入模板变量说明（JSON格式）',
    descriptionPlaceholder: '请输入模板描述',
    contentBusinessHint: '模板内容就是客户收到的消息结构，系统会自动替换变量后发送。',
    loadExample: '点击加载示例模板',
  },
  notes: {
    smsAliyunCode: '模板代码需与服务商平台模板保持一致。',
    wechatTemplateId: '模板 ID 需在微信公众平台申请。',
    emailNoCode: '邮件模板无需填写模板代码。',
    smsProviderRequired: '短信模板需选择服务商。',
    wechatProviderSuggested: '微信模板建议固定使用“微信”服务商。',
    emailNoProvider: '邮件模板无需选择服务商。',
    smsSignHint: '短信模板通常需要匹配服务商平台上的签名。',
  },
  options: {
    sms: '短信',
    wechat: '微信',
    email: '邮件',
    aliyun: '阿里云',
    tencent: '腾讯云',
    wechatProvider: '微信',
    enabled: '启用',
    disabled: '禁用',
    unset: '未设置',
  },
  feedback: {
    loadFailed: '加载模板列表失败',
    deleteFailed: '删除失败',
    enabledSuccess: '通知模板已启用',
    disabledSuccess: '通知模板已禁用',
    toggleFailed: '操作失败',
  },
  validation: {
    nameRequired: '请填写通知模板名称',
    typeRequired: '请选择通知模板类型',
    contentRequired: '请填写通知模板内容',
  },
  examples: {
    aliyunLoaded: '已加载阿里云短信模板示例',
    tencentLoaded: '已加载腾讯云短信模板示例',
    providerRequired: '请先选择服务商（阿里云或腾讯云）',
    wechatLoaded: '已加载微信模板示例',
    emailLoaded: '已加载邮件模板示例',
    typeRequired: '请先选择模板类型',
  },
  placeholders: {
    smsAliyunContent: '请输入JSON格式，如：{"code":"${matterName}"}',
    smsTencentContent: '请输入数组格式，如：["${matterName}","${accessUrl}"]',
    smsDefaultContent: '请输入模板内容（JSON格式）',
    wechatContent: '请输入JSON格式，符合微信模板消息字段结构',
    emailContent: '请输入HTML格式，支持变量：${matterName}、${accessUrl}、${clientName}',
    defaultContent: '请输入模板内容',
    aliyunCode: '请输入模板代码（如：SMS_123456789）',
    tencentCode: '请输入模板ID（如：123456）',
    providerFirst: '请先选择服务商',
    wechatCode: '请输入模板ID（如：abc123def456）',
    defaultCode: '请输入模板代码',
  },
  formatHints: {
    smsAliyun: '格式：JSON对象，变量名必须与阿里云平台模板变量一致。',
    smsTencent: '格式：JSON数组，数组顺序必须与腾讯云模板变量顺序一致。',
    chooseProvider: '请选择服务商后查看格式说明',
    wechat: '格式：JSON对象，需符合微信模板消息的字段结构。',
    email: '格式：HTML格式，可直接组合完整邮件内容。',
    chooseType: '请先选择模板类型',
  },
} as const

export const ADMIN_API_KEY_TEXTS = {
  intro: '创建与轮换密钥；下方为管理系统对接地址与回调校验说明。',
  actions: {
    create: '新增密钥',
    goToConfig: '前往系统配置',
    editTitle: '编辑API密钥',
    createTitle: '新增API密钥',
    successTitle: 'API 密钥创建成功',
    successClose: '我已保存，关闭',
  },
  guide: {
    title: 'API 对接信息',
    tag: '主入口',
    apiAddressMissing: '未配置（请在「系统配置」中设置 system.base-url）',
    apiAddressHint: '注：管理系统配置时直接使用此地址，无需添加 /api',
    authLabel: '认证方式',
    usageLabel: '使用说明',
    usageItems: [
      '在下方创建 API 密钥',
      '将 API 地址、API 密钥和 API Secret 提供给管理系统管理员',
      '在管理系统的“外部系统集成”中完成客户服务系统配置',
      '客户服务系统回调管理系统时，优先使用 API Secret 参与校验',
    ],
  },
  stats: {
    total: '密钥总数',
    totalHint: '当前所有对接密钥的总量。',
    enabled: '启用中',
    enabledHint: '处于可用状态，可直接用于系统集成。',
    disabled: '已禁用',
    disabledHint: '已停用，不再允许对外调用。',
    expired: '已过期',
    expiredHint: '已达到过期时间，建议及时轮换。',
  },
  filter: {
    title: '筛选与治理',
    desc: '根据启用状态快速筛出需要轮换、停用或检查的密钥。',
    statusPlaceholder: '请选择状态',
  },
  table: {
    title: '密钥列表',
    neverExpires: '永不过期',
  },
  modal: {
    keyNamePlaceholder: '请输入密钥名称',
    expiresPlaceholder: '选择过期时间（留空表示永不过期）',
    secretWarnTitle: 'Secret 仅在创建时显示一次完整值',
    secretWarnBody1: '出于安全考虑，编辑时无法查看完整 Secret。',
    secretWarnBody2: '创建密钥后请立即复制保存；如忘记 Secret，需要删除并重新创建。',
    successAlert: '请立即复制保存以下密钥信息，关闭后将无法再次查看 Secret。',
  },
  validation: {
    nameRequired: '请填写 API 密钥名称',
    nameTooLong: 'API 密钥名称不能超过 50 个字符',
    nameInvalid: 'API 密钥名称仅支持中英文、数字、下划线和横杠',
    missingId: '无法获取密钥ID',
  },
  toggle: {
    enabled: 'API密钥已启用',
    disabled: 'API密钥已禁用',
  },
} as const

export const ADMIN_NOTIFICATION_HISTORY_TEXTS = {
  intro: '按渠道与状态筛选；失败记录可优先处理。',
  stats: {
    total: '总数',
    success: '成功',
    failed: '失败',
    pending: '待发送',
  },
  channelSummary: {
    sms: '短信',
    wechat: '微信',
    email: '邮件',
    success: '成功',
    failed: '失败',
  },
  filter: {
    title: '筛选',
    matterIdLabel: '项目ID',
    matterIdPlaceholder: '请输入项目ID',
    clientIdLabel: '客户ID',
    clientIdPlaceholder: '请输入客户ID',
    typeLabel: '通知类型',
    typePlaceholder: '请选择通知类型',
    statusLabel: '状态',
    statusPlaceholder: '请选择状态',
    dateRangeLabel: '时间范围',
    totalPrefix: '共 ',
    totalSuffix: ' 条',
  },
  tableTitle: '发送记录',
  table: {
    id: 'ID',
    matterId: '项目ID',
    notificationType: '通知类型',
    recipient: '接收人',
    status: '状态',
    sentAt: '发送时间',
    createdAt: '创建时间',
    retryInfo: '重试信息',
    errorMessage: '错误信息',
    action: '操作',
  },
  typeOptions: {
    sms: '短信',
    wechat: '微信',
    email: '邮件',
  },
  statusOptions: {
    pending: '待发送',
    success: '成功',
    failed: '失败',
  },
  retry: {
    button: '重试',
    label: '重试',
    nextRetry: '下次重试',
    missingMatter: '无法获取项目ID',
    success: '已触发重试发送',
    failed: '重试发送未完成，请稍后重试',
  },
  feedback: {
    statsLoadFailed: '加载统计信息失败',
  },
  loadFailed: '通知记录加载未完成，请稍后重试',
} as const

export const ADMIN_LOGIN_TEXTS = {
  placeholders: {
    username: '请输入用户名',
    password: '请输入密码',
    captcha: '请输入验证码',
    captchaLoading: '加载中...',
  },
  validation: {
    usernameRequired: '请输入用户名',
    usernameLength: '用户名长度为 3-32 个字符',
    usernamePattern: '用户名只允许字母、数字和下划线',
    passwordRequired: '请输入密码',
    passwordLength: '密码长度为 8-64 个字符',
    captchaRequired: '请输入验证码',
    captchaLength: '验证码长度为 4-6 个字符',
  },
  feedback: {
    captchaFormatError: '验证码响应异常，请刷新页面后重试',
    captchaLoadFailed: '验证码加载未完成，请刷新页面后重试',
    loginSuccess: '登录成功',
    loginFailed: '登录失败，请检查用户名和密码',
  },
} as const
