export const UI_TEXTS = {
  loginTitle: '法律服务管理门户',
  loginSubtitle: '专业 · 高效 · 安全',
  matterManagement: '案件事务管理',
  progressNoticeCenter: '进度告知中心',
  evidenceSubmission: '证据/文书提报',
  autoRetryStrategy: '自动补发策略',
  search: '检索',
  refresh: '刷新',
  reset: '重置',
  save: '保存',
  back: '返回',
  backToList: '返回列表',
  logout: '退出登录',
  viewStatistics: '查看统计',
  collapseStatistics: '收起统计',
  copyPath: '复制路径',
  delete: '作废',
  remove: '移除',
  loginButton: '进入管理门户',
} as const

export const UI_ACTION_TEXTS = {
  continueUsing: '继续使用',
  logoutNow: '立即登出',
} as const

export const UI_FEEDBACK_TEXTS = {
  autoLogout: '会话因长时间未操作已安全结束',
  logoutSuccess: '已安全退出管理门户',
  operationFailed: '当前操作未完成，请稍后重试',
  copySuccess: '信息已复制到剪贴板',
  copyFailed: '复制未完成，请手动处理',
  matterRevoked: '案件访问权限已作废',
  verificationRevoked: '函件验证权限已作废',
  configCreated: '配置项已创建',
  configUpdated: '配置项已更新',
  configDeleted: '配置项已移除',
  configLoadFailed: '配置数据加载未完成，请稍后重试',
  configSaveFailed: '配置未生效，请稍后重试',
  templateCreated: '通知模板已创建',
  templateUpdated: '通知模板已更新',
  templateDeleted: '通知模板已移除',
  apiKeyUpdated: 'API 密钥已更新',
  apiKeyDeleted: 'API 密钥已移除',
  apiKeyListLoadFailed: 'API 密钥列表加载未完成，请稍后重试',
  systemInfoLoadFailed: '系统信息加载未完成，请稍后重试',
  dependencyStatusLoadFailed: '依赖状态加载未完成，请稍后重试',
  initLoadFailed: '初始化配置加载未完成，请稍后重试',
  initSaved: '初始化配置已生效',
  initSaveFailed: '初始化配置未生效，请稍后重试',
  profilePasswordUpdated: '密码已更新，请重新登录',
  fileRemoved: '文件已移除',
  fileRemoveFailed: '文件移除未完成，请稍后重试',
  batchRemoveFailed: '批量移除未完成，请稍后重试',
  cleanupFailed: '过期文件清理未完成，请稍后重试',
  backupCreateFailed: '数据库备份创建未完成，请稍后重试',
  backupDeleteFailed: '备份移除未完成，请稍后重试',
  backupDownloadFailed: '备份下载未完成，请稍后重试',
  exportSuccess: '导出文件已生成',
  exportFailed: '导出未完成，请稍后重试',
} as const

export const UI_CONFIRM_TEXTS = {
  revokeMatter: '确定要作废该案件访问权限吗？',
  revokeVerification: '确定要作废该函件验证权限吗？',
  removeApiKey: '确定要移除此 API 密钥吗？',
  removeTemplate: '确定要移除此通知模板吗？',
  removeConfig: '确定要移除此配置项吗？',
  removeFile: '确定要移除此文件吗？',
  batchRemoveFilesTitle: '确认批量移除文件',
  createBackupTitle: '确认创建数据库备份',
  createBackupContent: '备份过程可能持续数分钟，期间请勿执行其他数据库变更操作。确认继续吗？',
} as const

export const UI_EMPTY_TEXTS = {
  noDataTitle: '暂无可展示的数据',
  noDataHint: '可稍后刷新，或调整筛选条件后再试。',
  noTableDataHint: '当前列表暂无记录，可调整筛选条件或等待数据同步。',
} as const
